### ISSUE TITLE
Is measurement on all qubits implied?

### ISSUE THREAD

**Issue by we-taper** [aws/amazon-braket-sdk-python#158]
Hi braket developers, I am looking at this [document](https://github.com/aws/amazon-braket-sdk-python#running-a-circuit-on-an-aws-simulator) but I am confused by it.
Since there is no measurements on qubits in the circuit, I do not expect to get any returns from running the circuit. But the code result seems to implied that all qubits are measured in the end of the experiment.
- Is this implied on all qubit-based quantum backends? Can we clarify this in the document.
- Is there a way to prevent measurements on all qubits (which may cause unnecessary cross-talk error during measurements)?

**Comment by kshitijc** [comment]
Hello!
Yes, the default behavior (if no result types are specified) is to simply return the measurements over all qubits at the end of the experiment. The SDK also provides the ability to request specific result types on a subset of qubits. Please refer to the documentation [here](https://amazon-braket-sdk-python.readthedocs.io/en/latest/_apidoc/braket.circuits.result_types.html#module-braket.circuits.result_types) to see the available result types.

**Comment by avawang1** [comment]
Thanks for reaching out.

If shots > 0, then all qubits are measured for the local simulator, cloud simulator SV1 and QPUs. The result type values are calculated from the measurements. Note that for result types requiring a different basis than Pauli Z, then additional basis rotation gates are applied to the qubits of the result type. The measurements are for all qubits after any basis rotation gates have been applied.

If shots == 0 for simulators, only the result types are returned.

**Comment by we-taper** [comment]
Thanks @avawang1 for this information. I am quite curious if this is due to hardware limitations?
This a bit confusing for me, because if it is a hardware limitation then why should the simulators (local or SV1) also give back all qubit measurement results?
Also, since the technology of partial measurement/non-demolition measurement is under development (I believe in some quantum architectures), may I expect to use this SDK to change at that time?

**Comment by avawang1** [comment]
For shots > 0, we are treating SV1 and the local simulator as QPU-like, which means that `result.measurements` is available in addition to `result.values` if result types were specified. 

If there are any changes to the SDK in the future, please be assured that we will announce them in the release notes.

**Comment by we-taper** [comment]
Excellent! Thanks for the explanations.
