### ISSUE TITLE
Initialising arbitrary qubit state

### ISSUE THREAD

**Issue by LorcanConlon** [aws/amazon-braket-sdk-python#208]
Hi, 
This may be the wrong place for questions/issues like this, and if so I apologise, but I cannot seem to find a way to initialise any arbitrary qubit state on aws braket. I can only start with a |0> state and then convert to a |1> state (or something in between) through gates. 

What I desire to do can be done on IBMQ experience with initialize(). Is there something similar on AWS braket? If not would it be possible to create such a function.

Kind regards

**Comment by LorcanConlon** [comment]
Hi, 
I have came across the arbitrary unitary gate and was using it for another application so I should be able to use this to initialize any state. My concern is just that in doing this for the real world quantum computers I wish to access will introduce an extra unitary which will result in unnecessary extra noise. I would have thought the real world devices were capable of initialising any arbitrary start state so possibly some function of this form would be useful. If you wish to use the function I will create please let me know.

Many thanks

**Comment by kshitijc** [comment]
Glad to hear that the unitary gate unblocks you. I'm not quite sure if the real world devices can be initialized to any arbitrary state in a noise-free manner. I took a brief look at [qiskit's initialize](https://qiskit.org/documentation/_modules/qiskit/extensions/quantum_initializer/initializer.html#Initialize) method and it seems like they derive the set of gates which lead to the specified input state vector. 
Please feel free to open a pull request if you would like to contribute. Our contribution guidelines can be found [here](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md). Thanks!

**Comment by wrasmuss** [comment]
This issue appears to be resolved. Closing.
