### ISSUE TITLE
Get the unitary for an entire `Circuit`

### ISSUE THREAD

**Issue by singular-value** [aws/amazon-braket-sdk-python#209]
**Describe the feature you'd like**
It would be great if a `Circuit` could return its 2^n by 2^n unitary (by multiplying across the moments)
(Please let me know if this feature already exists)

**How would this feature be used? Please describe.**
I'm looking to use this feature in unit tests for a function converting between different quantum circuit languages (qiskit, cirq, etc.)

**Comment by wrasmuss** [comment]
> **Describe the feature you'd like**
> It would be great if a `Circuit` could return its 2^n by 2^n unitary (by multiplying across the moments)
> (Please let me know if this feature already exists)
> 
> **How would this feature be used? Please describe.**
> I'm looking to use this feature in unit tests for a function converting between different quantum circuit languages (qiskit, cirq, etc.)

@singular-value Thanks  for providing your input. This feature does not currently exists but I will add it to our queue for future consideration. You are also free to create a pull request that we will review and consider merging. We would likely make this a feature of the LocalSimulator rather than the circuit itself.

**Comment by singular-value** [comment]
👍 right would make sense to include in `LocalSimulator`

**Comment by indisoluble** [comment]
Hi all,

I would like to give this feature a try. If I create the MR, will you consider to merge it? Maybe you already evaluated this feature and you are not interested on it ... for now :)

Regards.

**Comment by kshitijc** [comment]
Yes, we welcome community contributions and will consider your pull request. You might find the [contribution guidelines](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) helpful. Please let us know if you run into issues. Thanks!
