### ISSUE TITLE
Circuit equality should consider the arguments of the gates

### ISSUE THREAD

**Issue by singular-value** [aws/amazon-braket-sdk-python#213]
**Describe the feature you'd like**
This should return `False`:
```
In [1]: c1 = braket.circuits.Circuit().rz(0, np.pi/3)           

In [2]: c2 = braket.circuits.Circuit().rz(0, np.pi/5)           

In [3]: c1 == c2                                                
Out[3]: True
``` 
The call stack for circuit equality ultimately relies on equality of gates. However, 
The current [\_\_eq__](https://github.com/aws/amazon-braket-sdk-python/blob/main/src/braket/circuits/gate.py#L54) only checks if the instructions are of the same type/name. As a result, `c1` and `c2` are considered equal, even though they have different arguments.

**How would this feature be used? Please describe.**
Like #209, this would help with unit tests and also be good for general circuit construction sanity.

**Comment by virajchau** [comment]
Thanks for providing your input. This feature does not currently exists but we will add it to our queue for future consideration. You are also free to create a pull request that we will review and consider merging.

**Comment by speller26** [comment]
Will be fixed in #216

**Comment by speller26** [comment]
#216 has been merged; angles are now considered for equality

**Comment by singular-value** [comment]
Thanks!
