### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ioannist** [aws/amazon-braket-sdk-python#232]
All the links in this page are broken:

https://github.com/aws/amazon-braket-sdk-python/blob/main/doc/examples-quantum-annealing-dwave.rst

**Comment by virajchau** [comment]
Solved with 

> https://github.com/aws/amazon-braket-sdk-python/pull/233

I will proceed to close this issue and mark it as resolved. Thanks for notifying, please reopen if you still encounter this issue.
