### ISSUE TITLE
Index 'result_types' syntax error in repr() output

### ISSUE THREAD

**Issue by kjacky** [aws/amazon-braket-sdk-python#252]
**Describe the bug**
The `repr()` output of a circuit with result types has a syntax error at around the 'result_types' index.

**To reproduce**
```
from braket.circuits import Circuit
circ = Circuit().h(0).probability(0)
print(repr(circ))
"""
Output:
Circuit('instructions': [Instruction('operator': H('qubit_count': 1), 'target': QubitSet([Qubit(0)]))]result_types': [Probability(target=QubitSet([Qubit(0)]))])
"""
```

**Expected behavior**
The output should be
```
Circuit('instructions': [Instruction('operator': H('qubit_count': 1), 'target': QubitSet([Qubit(0)]))], 'result_types': [Probability(target=QubitSet([Qubit(0)]))])
```

with `, '` added before `result_types`.

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.6.5
- **Amazon Braket Python Schemas version**: 1.1.3
- **Amazon Braket Python Default Simulator version**: (not on simulator)
- **Python version**: 3.8.5

**Comment by kshitijc** [comment]
Fixed with #254
