### ISSUE TITLE
Control an abstract circuit

### ISSUE THREAD

**Issue by Devonien** [aws/amazon-braket-sdk-python#259]
Is there a method in braket (especially in braket.circuits) such that if *U* is an instance of the *Circuit* class, then U.control() refers to the controlled version of this circuit ?

**Comment by AjinkyaGawali** [comment]
Hello, Thanks for reaching out! We are sorry but currently we don't support anything like that yet, but it does sound interesting.

**Comment by kshitijc** [comment]
While we don't yet offer control modifiers for gates (or abstract circuits), it might be possible for you to utilize the arbitrary Unitary gate to achieve this by passing in the matrix representing the controlled version of the unitary for the circuit (The unitary representing the circuit can be obtained using the method `circuit.as_unitary()`). 

For instance:
```
# 1-qubit circuit with several gates
circuit = Circuit().h(0).x(0).xx(0)....

# Unitary matrix representing this circuit
unitary = circuit.as_unitary()

# Controlled version of this matrix (with 1 qubit control) should look like:
# [[1, 0, 0, 0],
#  [0, 1, 0, 0],
#  [0, 0, a, b],
#  [0, 0, c, d]])
# where a, b, c, d are elements of the `unitary` matrix.
controlled_unitary = np.pad(np.eye(2), ((0, 2), (0, 2))) + np.pad(unitary, ((2, 0), (2, 0)))

# Circuit representing the controlled version
controlled_circuit = Circuit().unitary(targets=[0, 1], matrix=controlled_unitary)
```

**Comment by kshitijc** [comment]
Hello @Devonien! Does the suggestion above work for you? If not, we'd like to hear more about your use case to see if there are other alternatives we could try.

**Comment by virajchau** [comment]
I will proceed to close this issue and mark it as resolved. Thanks for reaching out, please reopen if you didn't find resolution for your problem.
