### ISSUE TITLE
[SMALL] Device Availability

### ISSUE THREAD

**Issue by christianbmadsen** [aws/amazon-braket-sdk-python#269]
Today you can get device availability programmatically using “device.properties.service.executionWindows”. See an example [here](https://github.com/aws/amazon-braket-examples/blob/bc490ef734893b00444a380ece95a471532e89c1/examples/braket_features/Getting_Devices_and_Checking_Device_Properties.ipynb). However, there are multiple ExecutionDay values such as EVERYDAY for Rigetti and WEEKDAY for IonQ, so you have to parse all patterns.

**Objective** Create a function that shows current availability for a certain device (Available/Not available). The function should base the response on both the execution windows and the actual device status (device.status).

_Note: We expect a SMALL task to take hours or a few days to complete dependent on your level of familiarity with the Braket SDK._

**Comment by kshitijc** [comment]
This has been released in [v1.12.0](https://github.com/aws/amazon-braket-sdk-python/releases/tag/v1.12.0). Huge thanks to @surfkansas for this contribution 🎉 !
