### ISSUE TITLE
[SMALL] Return failure reason as part of the status for failed quantum tasks

### ISSUE THREAD

**Issue by christianbmadsen** [aws/amazon-braket-sdk-python#270]
When a task fails a user would like to know the information in failureResult. However, this is not easy to find and should be returned automatically when a task fails.

Objective Modify the .state() returned in the Braket SDK by a quantum task in case of a failure to include the failureReason.

If you load a task today and it was in a failed state the output will contain a statement that the task failed, but not a failure reason eg.,

```
task_id = "arn:aws:braket:us-east-1:ACCOUNTID:quantum-task/UUID" 
task_load = AwsQuantumTask(arn=task_id) 
status = task_load.state()
```

Returns
Task is in terminal state FAILED and no result is available

For a failed state this call should add the actual failure reason which is already available in the task meta data. What you do at this point to get the failure reason is

```
metadata = task_load.metadata()
failure_reason = metadata['failureReason']
print(failure_reason)
```

Which might give you something like
```
Predicted runtime based on best contraction path found exceeds TN1 limit [current limit=xx]. Single-shot FLOPS estimate = 2^88
```

_Note: We expect a small task to take hours or a few days to complete dependent on your level of familiarity with the Braket SDK._

**Comment by math411** [comment]
https://github.com/aws/amazon-braket-sdk-python/pull/275
