### ISSUE TITLE
No Region Error

### ISSUE THREAD

**Issue by epelofske-LANL** [aws/amazon-braket-sdk-python#284]
**Describe the bug**
Running this code:

```
from braket.aws import AwsDevice
device = AwsDevice("arn:aws:braket:::device/qpu/rigetti/Aspen-9")
```

Gave this error:

```
botocore.exceptions.NoRegionError: You must specify a region.
```

I have setup the AWS CLI configuration as well.

**To reproduce**
Run the above code

**Expected behavior**

**Screenshots or logs**

**System information**
- **Amazon Braket Python SDK version**: `amazon-braket-sdk==1.9.5`
- **Amazon Braket Python Schemas version**: `amazon-braket-schemas==1.4.1`
- **Amazon Braket Python Default Simulator version**: `amazon-braket-default-simulator==1.3.0`
- **Python version**: 3.9

**Additional context**

**Comment by ajberdy** [comment]
Hi, the error message is communicating that you need to provide a region to boto. You can provide a default region for aws to use with the following terminal command:
```
aws configure set default.region us-west-2
```

**Comment by epelofske-LANL** [comment]
The error was solved by specifying the environment variable: `export AWS_PROFILE=YOUR_PROFILE_NAME`
