### ISSUE TITLE
Aspen-10 programs with a verbatim_box pass validation but fail to execute

### ISSUE THREAD

**Issue by eth-n** [aws/amazon-braket-sdk-python#293]
Hi, it seems like the new Rigetti machine is not able to accept the verbatim_box instruction. This behavior interferes with certain procedures, such as the noise mitigation tool Mitiq. Additionally, the validator does not error out early, so there is instead a failure at the device compiler I think, which returns _very_ little information about what the problem could be. It wasn't too easy to isolate this problem from within a more complicated procedure when I thought this feature was working.

**To reproduce**
Here is a full program (less redactions) to run the same simple circuit without and then with a verbatim box.
```python3
import boto3
from braket.aws import AwsDevice, AwsSession
from braket.circuits import Circuit
from braket.circuits.gates import *

session = boto3.Session(profile_name="REDACTED", region_name="us-west-1")
s3 = session.client("s3")
brkt = session.client("braket")
braket_aws_session = AwsSession(session, brkt)

BUCKET = "amazon-braket-REDACTED-us-west-1"
device = AwsDevice("arn:aws:braket:::device/qpu/rigetti/Aspen-10", aws_session=braket_aws_session)

print("Native gates for this device:", device.properties.paradigm.nativeGateSet)

# SAME ACROSS REGIONS
KEY_PREFIX = "REDACTED"
s3_folder = AwsSession.S3DestinationFolder(BUCKET, KEY_PREFIX)

repro_ckt_1q = Circuit().rx(0, np.pi/2).z(0).rz(0, 0.76543)
verbatim_ckt = Circuit().add_verbatim_box(repro_ckt_1q)
print("circuits:")
print("normal:")
print(repro_ckt_1q)
print()
print("verbatim:")
print(verbatim_ckt)

print("\n##########")
print("normal task, force qubit 0")
task = device.run(repro_ckt_1q, s3_folder, disable_qubit_rewiring=True, shots=10)
res = task.result()
print("program compiled for device:")
print(res.additional_metadata.rigettiMetadata.compiledProgram)
print()
print("measurement probs:")
print(res.measurement_probabilities)

print("\n##########")
print("verbatim task")
task = device.run(verbatim_ckt, s3_folder, disable_qubit_rewiring=True, shots=10)
res = task.result()
print(res.additional_metadata.rigettiMetadata.compiledProgram)
print(res.measurement_probabilities)
```

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

```
Native gates for this device: ['RX', 'RZ', 'CZ', 'CPHASE', 'XY']
circuits:
normal:
T  : |   0    |1|    2    |
                           
q0 : -Rx(1.57)-Z-Rz(0.765)-

T  : |   0    |1|    2    |

verbatim:
T  : |      0      |   1    |2|    3    |     4     |
                                                     
q0 : -StartVerbatim-Rx(1.57)-Z-Rz(0.765)-EndVerbatim-

T  : |      0      |   1    |2|    3    |     4     |

##########
normal task, force qubit 0
program compiled for device:
DECLARE ro BIT[1]
PRAGMA INITIAL_REWIRING "NAIVE"
RESET
RX(pi/2) 0
RZ(-2.376162653589793) 0
MEASURE 0 ro[0]

measurement probs:
{'0': 0.6, '1': 0.4}

##########
verbatim task

Task is in terminal state FAILED and no result is available.
Task failure reason is: Failed to compile task; device: Aspen-10.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-3205fae90de1> in <module>
     39 task = device.run(verbatim_ckt, s3_folder, disable_qubit_rewiring=True, shots=10)
     40 res = task.result()
---> 41 print(res.additional_metadata.rigettiMetadata.compiledProgram)
     42 print(res.measurement_probabilities)

AttributeError: 'NoneType' object has no attribute 'additional_metadata'
```

**Expected behavior**
I would expect any of: correct execution of both tasks, the validator to fail when the submitted circuit has a verbatim box (or any other instruction that is disallowed, if any others are missing), or more complete error information (`task failure: failed to compile` was almost a dead end for me when I was debugging).

A natural followup question is whether verbatim boxes are still supposed to be supported on the Aspen-10 device. Otherwise, no currently available machine supports these instructions, right?

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.11.0
- **Amazon Braket Python Schemas version**: 1.5.0
- **Amazon Braket Python Default Simulator version**: n/a
- **Python version**: 3.8.11

Thank you!

**Comment by jheckey** [comment]
Hi @eth-n,

We're very sorry to hear this. Can you provide a task ARN to help us with root causing your issue?

-Thanks,
-@jheckey

**Comment by jheckey** [comment]
I see the issue with your circuit: `Z` is not a supported native gate. You can see the supported native gate set in the Device Capabilities for the device in the Braket SDK using:

```
device = AwsDevice("arn:aws:braket:::device/qpu/rigetti/Aspen-10")
device.properties.paradigm.nativeGateSet
```

Or from the CLI:

```
aws --region us-west-1 \
    braket get-device \
    --device-arn arn:aws:braket:::device/qpu/rigetti/Aspen-10 | \
    jq .deviceCapabilities | \
    jq -r . | \
    jq -r .paradigm.nativeGateSet
```

However, this circuit should have resulted in a validation error in the service and no tasking being created. We are continuing to investigate the service side issue.

**Comment by eth-n** [comment]
Right, sorry. It looks like I got ahead of myself with my example to make it obvious that the circuit was being compiled to something different in the first case. It also fails with an identity gate there:

```
Native gates for this device: ['RX', 'RZ', 'CZ', 'CPHASE', 'XY']
circuits:
normal:
T  : |  0  |
            
q0 : -Rx(0)-

T  : |  0  |

verbatim:
T  : |      0      |  1  |     2     |
                                      
q0 : -StartVerbatim-Rx(0)-EndVerbatim-

T  : |      0      |  1  |     2     |

##########
normal task, force qubit 0
program compiled for device:
DECLARE ro BIT[1]
PRAGMA INITIAL_REWIRING "NAIVE"
RESET
MEASURE 0 ro[0]


measurement probs:
{'0': 1.0}

##########
verbatim task

Task is in terminal state FAILED and no result is available.
Task failure reason is: Failed to compile task; device: Aspen-10.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-13f979fbd759> in <module>
     42 task = device.run(verbatim_ckt, s3_folder, disable_qubit_rewiring=True, shots=10)
     43 res = task.result()
---> 44 print(res.additional_metadata.rigettiMetadata.compiledProgram)
     45 print(res.measurement_probabilities)

AttributeError: 'NoneType' object has no attribute 'additional_metadata'
```

**Comment by krneta** [comment]
Hi @eth-n ,

We really appreciate your feedback.

I was able to get your example code (above) working once I removed the z gate. 

However, we've updated our responses to make it much more clear why verbatim blocks are failing in this way. Would you mind trying again and, if you're still experiencing an issue using only an Rx gate, let us know what the error output is?

**Comment by eth-n** [comment]
Sure thing, I'll update when the device is online next. Did you run it on Aspen 11? 10 is retired already.

**Comment by krneta** [comment]
Yes, I ran it on Aspen 11.

Thank you!

**Comment by kshitijc** [comment]
Hello @eth-n! Checking in to see if you're still facing any issues here.

**Comment by christianbmadsen** [comment]
Resolving this issue since we no longer offer access to Aspen-10 and Aspen-11 was verified. @eth-n of course raise another issue if anything else comes up. Thanks again for your contribution to this repository!
