### ISSUE TITLE
Potential issues around dependancy on "amazon-braket-schemas"

### ISSUE THREAD

**Issue by GenericUser127** [aws/amazon-braket-sdk-python#294]
I'm not sure if there is an issue with dependancies or I did something wrong but I had an older version of the Braket-sdk installed, I then pip installed the latest version of the Braket-sdk, but my "amazon-brakes-schemas" was not updated.

This resulted in an error where this line failed to import:
https://github.com/aws/amazon-braket-sdk-python/blob/main/src/braket/aws/aws_quantum_task.py#L30

Issue was fixed when I manually updated to the latest "amazon-brakes-schemas"

**Comment by kshitijc** [comment]
Thanks for reaching out @GenericUser127. We recommend using the following command for updating the SDK:
`pip install amazon-braket-sdk --upgrade --upgrade-strategy eager` as specified in the [package README](https://github.com/aws/amazon-braket-sdk-python#updating-the-amazon-braket-python-sdk). Let us know if this doesn't help.
