### ISSUE TITLE
ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ ls bin           CODE_OF_CONDUCT.md  CONTRIBUTING.md  examples  MANIFEST.in  pyproject.toml  setup.cfg  src   tox.ini CHANGELOG.md  CODEOWNERS          doc              LICENSE   NOTICE       README.md       setup.py   test ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ pip install amazon-braket-sdk Collecting amazon-braket-sdk   Could not find a version that satisfies the requirement amazon-braket-sdk (from versions: ) No matching distribution found for amazon-braket-sdk ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ python setup.py install Traceback (most recent call last):   File "setup.py", line 14, in <module>     from setuptools import find_namespace_packages, setup ImportError: cannot import name find_namespace_packages ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ 

### ISSUE THREAD

**Issue by iajzenszmi** [aws/amazon-braket-sdk-python#296]
![Screenshot from 2022-01-05 16-32-07](https://user-images.githubusercontent.com/5051767/148165468-55c7d88d-65be-4b05-a507-c0c82f41f37e.png)
![Screenshot from 2022-01-05 16-33-10](https://user-images.githubusercontent.com/5051767/148165473-5d8445d5-49c2-4d5e-9eba-57aab619a3c4.png)
*ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ ls
bin           CODE_OF_CONDUCT.md  CONTRIBUTING.md  examples  MANIFEST.in  pyproject.toml  setup.cfg  src   tox.ini
CHANGELOG.md  CODEOWNERS          doc              LICENSE   NOTICE       README.md       setup.py   test
ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ pip install amazon-braket-sdk
Collecting amazon-braket-sdk
  Could not find a version that satisfies the requirement amazon-braket-sdk (from versions: )
No matching distribution found for amazon-braket-sdk
ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from setuptools import find_namespace_packages, setup
ImportError: cannot import name find_namespace_packages
ian@ian-HP-Stream-Laptop-11-y0XX:~/braket/amazon-braket-sdk-python$ 
*Describe the bug**
The bug is "No matching distribution found for amazon-braket-sdk"
ImportError: cannot import name find_namespace_packages

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
~/braket/amazon-braket-sdk-python$ python setup.py install 
in linux bash shell.
~/braket/amazon-braket-sdk-python$ pip install amazon-braket-sdk

**Expected behavior**
The errors messages should not be output  and the install run to completion.
**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**:
- **Amazon Braket Python Schemas version**:
- **Amazon Braket Python Default Simulator version**:
- **Python version**: 2.7.17 and  3.6.9

**Additional context**

**Comment by speller26** [comment]
The minimum supported Python version is 3.7; 2.7.17 and 3.6.9 won't work.
