### ISSUE TITLE
Braket SDK requires amazon-braket-schemas-python >= 1.10.0

### ISSUE THREAD

**Issue by math411** [aws/amazon-braket-sdk-python#377]
**Describe the bug**
Braket SDK requires amazon-braket-schemas-python >= 1.10.0.  A change in [amazon-braket-schemas](https://github.com/aws/amazon-braket-schemas-python) breaks customers attempting to call `AwsDevice.get_devices()` for versions before 1.10.0.

**To fix**
Locally:
`pip install --upgrade amazon-braket-schemas`

From a Braket Notebook Instance:
`!pip install --upgrade amazon-braket-schemas`

**Comment by christianbmadsen** [comment]
Closing as this issue is now stale.
