### ISSUE TITLE
LocalQuantumJob.create() fails when running on Windows

### ISSUE THREAD

**Issue by marcianomoreno** [aws/amazon-braket-sdk-python#440]
**Describe the bug**
Executing a Python script invoking LocalQuantumJob.create() in Windows 10 fails with the following output (abbreviated, full log in logs section):
`
Error: No such container:path: d585762a076af1743e0ec5e794a2072e2ab211aa160330e7b7b1061bd1e39f58:\opt\ml\input\config
...
subprocess.CalledProcessError: Command '['docker', 'cp', 'C:\\Users\\Marciano\\AppData\\Local\\Temp\\tmpbm8fz453\\hyperparameters.json', 'd585762a076af1743e0ec5e794a2072e2ab211aa160330e7b7b1061bd1e39f58:/opt/ml/input/config/hyperparameters.json']' returned non-zero exit status 1.`

**To reproduce**

1. Create a test directory, such as c:\local-quantum-job
2. Copy the file [algorithm_script.py](https://github.com/aws/amazon-braket-examples/blob/main/examples/hybrid_jobs/0_Getting_started/algorithm_script.py) from Amazon Braket Examples to the test directory 
3. Create a Python script called `local-job.py` in the test directory invoking LocalQuantumJob.create(), with the following code:

`from braket.jobs.local.local_job import LocalQuantumJob

job = LocalQuantumJob.create(
    device = "arn:aws:braket:::device/quantum-simulator/amazon/sv1",
    source_module = r"C:\local-quantum-job\algorithm_script.py"
)`

4. Execute the Python script via `python local-job.py`

**Expected behavior**
The local job is executed successfully and the job results are presented in the terminal. Sample successful output:
`
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Pulling docker container image. This may take a while.
1.0-cpu-py37-ubuntu18.04: Pulling from amazon-braket-base-jobs
Digest: sha256:b8a5dac0e1bdbbd7bfbda367504443827c02b0b0154c541550fd0320e54cf6ba
Status: Image is up to date for 292282985366.dkr.ecr.us-east-1.amazonaws.com/amazon-braket-base-jobs:1.0-cpu-py37-ubuntu18.04
292282985366.dkr.ecr.us-east-1.amazonaws.com/amazon-braket-base-jobs:1.0-cpu-py37-ubuntu18.04
Boto3 Version:  1.22.7
Beginning Setup
Checking for Additional Requirements
Additional Requirements Check Finished
Running Code As Subprocess
Test job started.
Counter({'0': 87, '1': 13})
Counter({'1': 63, '0': 37})
Counter({'1': 81, '0': 19})
Counter({'1': 87, '0': 13})
Counter({'0': 100})
Test job completed.
Code Run Finished
f477ab1cd93f1e9cf5305cdd17bd123c156d61046aaefba19fb0f8d962e9f9b3
`

**Screenshots or logs**
Failed command output:
`
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Pulling docker container image. This may take a while.
1.0-cpu-py37-ubuntu18.04: Pulling from amazon-braket-base-jobs
Digest: sha256:b8a5dac0e1bdbbd7bfbda367504443827c02b0b0154c541550fd0320e54cf6ba
Status: Image is up to date for 292282985366.dkr.ecr.us-east-1.amazonaws.com/amazon-braket-base-jobs:1.0-cpu-py37-ubuntu18.04
292282985366.dkr.ecr.us-east-1.amazonaws.com/amazon-braket-base-jobs:1.0-cpu-py37-ubuntu18.04
Error: No such container:path: d585762a076af1743e0ec5e794a2072e2ab211aa160330e7b7b1061bd1e39f58:\opt\ml\input\config

d585762a076af1743e0ec5e794a2072e2ab211aa160330e7b7b1061bd1e39f58
Traceback (most recent call last):
  File "local-job.py", line 6, in <module>
    source_module = r"C:\src\marmo\aws-qc-workshop-082022\braket-sdk\algorithm_script.py"
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\site-packages\braket\jobs\local\local_job.py", line 151, in create
    env_variables = setup_container(container, session, **create_job_kwargs)
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\site-packages\braket\jobs\local\local_job_container_setup.py", line 47, in setup_container
    if _copy_hyperparameters(container, **creation_kwargs):
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\site-packages\braket\jobs\local\local_job_container_setup.py", line 181, in _copy_hyperparameters
    container.copy_to(str(file_path), "/opt/ml/input/config/hyperparameters.json")
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\site-packages\braket\jobs\local\local_job_container.py", line 207, in copy_to
    raise e
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\site-packages\braket\jobs\local\local_job_container.py", line 202, in copy_to
    ["docker", "cp", source, f"{self._container_name}:{destination}"]
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Marciano\.conda\envs\aws-braket\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'cp', 'C:\\Users\\Marciano\\AppData\\Local\\Temp\\tmpbm8fz453\\hyperparameters.json', 'd585762a076af1743e0ec5e794a2072e2ab211aa160330e7b7b1061bd1e39f58:/opt/ml/input/config/hyperparameters.json']' returned non-zero exit status 1.
`

**System information**
- **Amazon Braket Python SDK version**: 1.29.2
- **Amazon Braket Python Schemas version**: 1.10.2
- **Amazon Braket Python Default Simulator version**: 1.7.2.post0
- **Python version**: 3.7.12
-  **Operating system**: Windows 10 21H2 (OS Build 19044.1889)
- **Docker version**: 20.10.17, build 100c701

**Additional context**

**Comment by marcianomoreno** [comment]
I am working on a PR for this issue. The integration tests fail on main branch. Please refer to the attached unit and integration test logs.
[aws-braket-sdk-unit-test.log](https://github.com/aws/amazon-braket-sdk-python/files/9530734/aws-braket-sdk-unit-test.log)
[aws-braket-sdk-int-test.log](https://github.com/aws/amazon-braket-sdk-python/files/9530735/aws-braket-sdk-int-test.log)

**Comment by ajberdy** [comment]
I'm seeing output for the integ tests "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?". Can you verify Docker is running when you're running these tests?

**Comment by marcianomoreno** [comment]
Yes, I will. Thanks @ajberdy

**Comment by marcianomoreno** [comment]
Logs from a session with Docker running. 
[aws-braket-sdk-unit-test.log](https://github.com/aws/amazon-braket-sdk-python/files/9531229/aws-braket-sdk-unit-test.log)
[aws-braket-sdk-int-test-1.log](https://github.com/aws/amazon-braket-sdk-python/files/9531230/aws-braket-sdk-int-test-1.log)

From the tail of the integration test:
`============ 83 passed, 26 warnings, 76 errors in 638.99s (0:10:38) ============
ERROR: InvocationError for command /home/linux/src/marcianomoreno/amazon-braket-sdk-python/.tox/integ-tests/bin/pytest test/integ_tests (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   integ-tests: commands failed
`

**Comment by marcianomoreno** [comment]
Integration tests with main branch fail on Windows with Docker running.
[integ-tests.log](https://github.com/aws/amazon-braket-sdk-python/files/9531647/integ-tests.log)

**Comment by marcianomoreno** [comment]
Addressed in PR#444
