### ISSUE TITLE
Failing to manage multiple profiles

### ISSUE THREAD

**Issue by Boniface316** [aws/amazon-braket-sdk-python#445]
**Describe the bug**
`AwsSession` fails to manage multiple profiles for QPU-related tasks. It only works if I move the credentials to the `default` profile. 

`QPUs = AwsDevice.get_devices(types=["QPU"], aws_session=aws_session)` is failing but `simulators = AwsDevice.get_devices(types=["SIMULATOR"], aws_session=aws_session)` is working. We created `aws_session` using the instruction provided in the [docs ](https://docs.aws.amazon.com/braket/latest/developerguide/braket-using-boto3-profiles-step-3.html). The only workaround is to move the credentials to `default` profile. 

Error message:
`ClientError: An error occurred (UnrecognizedClientException) when calling the SearchDevices operation: The security token included in the request is invalid`

**Comment by ajberdy** [comment]
Hi, thanks for documenting this issue! Would you mind sharing a code snippet that you are using that gives this error? If we can see how you're setting up the credentials and setting up the sessions, that will help with debugging. Please redact credentials of course

**Comment by ajberdy** [comment]
Yes, the setup looks good, just wanted to make sure I'm debugging the same scenario you're facing. Getting QPUs searches over multiple regions and involves copying the session, whereas simulators is more straightforward, so that gives a good start to where this edge case is cropping up. I'll take a look and see if I can get this fixed quickly. Thanks for sharing!

**Comment by Boniface316** [comment]
My profile is setup for only `us-east-1`. Its weird when it works fine for the `default` profile. 
Thank you!

**Comment by ajberdy** [comment]
Thanks for identifying this bug! Here is a PR with my fix: https://github.com/aws/amazon-braket-sdk-python/pull/446. It is not ready to merge as I need to update some of the adjacent unit tests, but feel free to install from source to unblock your development in the meantime.

**Comment by Boniface316** [comment]
@ajberdy its working! Thank you very much!
