### ISSUE TITLE
Support for Python 3.10 and 3.11

### ISSUE THREAD

**Issue by shahakL** [aws/amazon-braket-sdk-python#482]
**Describe the feature you'd like**
The Amazon Braket SDK is officially supported and tested on Python version 3.7-3.9. Support for newer versions 3.10 and 3.11 would allow integration with newer projects.

**How would this feature be used? Please describe.**
The SDK would be available to any project based on Python 3.10 or 3.11.

**Describe alternatives you've considered**

**Additional context**

**Comment by shahakL** [comment]
Would be solved by https://github.com/aws/amazon-braket-sdk-python/pull/485

**Comment by mdpratt** [comment]
Hi @shahakL thank you for your request. As you can see we are working on the migration but we do not have a timeline for when it will be ready. Please keep your eyes on https://github.com/aws/amazon-braket-sdk-python/pull/485 for the latest details.

**Comment by mdpratt** [comment]
Hi @shahakL, we're happy to let you know that Python 3.10 is now supported.

**Comment by shpface** [comment]
Support for 3.11 is added by #572.
