### ISSUE TITLE
setuptools should be explicitly added as a dependency

### ISSUE THREAD

**Issue by kwkbtr** [aws/amazon-braket-sdk-python#506]
**Describe the bug**

`src/braket/devices/local_simulator.py` imports `pkg_resources` (https://github.com/aws/amazon-braket-sdk-python/blob/105433edb22ad2ccb50afbb72fd74ccb8d8d63b9/src/braket/devices/local_simulator.py#L17), but it fails when `setuptools` is not installed.
`setuptools` can sometimes be missing, depending on how you create the (virtual) environment.
I think `setuptools` should be specified as a dependency explicitly, i.e. added to `install_requires` in `setup.py`.
In my case, I created the virtual environment with [Poetry](https://python-poetry.org/), with `amazon-braket-sdk` listed in  `pyproject.toml` (`[tool.poetry.dependencies]` section).
(Actually it seems to be an unintended behavior (cf. https://github.com/python-poetry/poetry/issues/6328), but I still think that the dependency should be explicitly specified.)

**To reproduce**

- Install [Poetry](https://python-poetry.org/)
- Set up a project with `poetry init`
- Add `amazon-braket-sdk` as a dependency: `poetry add amazon-braket-sdk`
- Remove `setuptools` manually: `poetry run pip uninstall setuptools`
- Run Python in the Poetry virtual environment: `poetry run python`
- Import `LocalSimulator`: `from braket.devices.local_simulator import LocalSimulator`
- (Cleanup) Exit Python and remove the virtual environment: `poetry env remove python`

**Expected behavior**

The import succeeds without errors.

**Screenshots or logs**

The following error occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/q/.cache/pypoetry/virtualenvs/t-UUQASyjB-py3.9/lib/python3.9/site-packages/braket/devices/__init__.py", line 15, in <module>
    from braket.devices.local_simulator import LocalSimulator  # noqa: F401
  File "/home/q/.cache/pypoetry/virtualenvs/t-UUQASyjB-py3.9/lib/python3.9/site-packages/braket/devices/local_simulator.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.35.5
- **Amazon Braket Python Schemas version**: 1.14.1.post0
- **Amazon Braket Python Default Simulator version**: 1.11.5.post0
- **Python version**: 3.9.9

**Additional context**

**Comment by speller26** [comment]
Thank you for raising the issue! I've created a PR to fix this.
