### ISSUE TITLE
Gate modifiers on local simulator through the BDK Circuit class

### ISSUE THREAD

**Issue by ajberdy** [aws/amazon-braket-sdk-python#523]
**Describe the feature you'd like**
The local simulator supports using OpenQASM gate modifiers through its OpenQASM interface. I would like to be able to use gate modifiers from the BDK Circuit class when using the local simulator.

**How would this feature be used? Please describe.**
Users could modify gates in a circuit as it is constructed. For example:
```python
circ = Circuit()
circ.ry(target=2, angle=11/7, control=[0, 1])
cirx.x(target=0, power=1/3)
```

**Describe alternatives you've considered**
This is currently attainable by using an OpenQASM string to define the circuit.

**Additional context**
I will begin working on the implementation for this feature on the branch [`feature/gate-modifiers`](https://github.com/aws/amazon-braket-sdk-python/tree/feature/gate-modifiers)

**Comment by christianbmadsen** [comment]
@ajberdy can this be closed based on #524 and #226 that are merged?
