### ISSUE TITLE
LocalSimulator allow for `braket.ir.ahs.Program` as input.

### ISSUE THREAD

**Issue by weinbe58** [aws/amazon-braket-sdk-python#564]
**Describe the feature you'd like**
I would like to be able to submit raw AHS IR objects into the `LocalSimulator`

**How would this feature be used? Please describe.**
I have code that generates Braket AHS IR directly, and I would like to run those tasks using the emulator to compare to running on Aquila. 

**Describe alternatives you've considered**
I could rewrite my code for generating tasks as `AnalogHamiltonianSimulations`, but this would require maintaining more code on my part. The LocalSimulator for braket AHS mode already uses the IR object to run the simulation so it shouldn't require much effort to change this. 

**Additional context**
I have a PR for this.

**Comment by kshitijc** [comment]
Closed by #565
