### ISSUE TITLE
Support quantum circuits on Device SV1 using `boto3-1.27.0`

### ISSUE THREAD

**Issue by maliasadi** [aws/amazon-braket-sdk-python#593]
Running the following PennyLane circuit,

``` python
import pennylane as qml

device = qml.device(
    "braket.aws.qubit",
    device_arn="arn:aws:braket:::device/quantum-simulator/amazon/sv1",
    wires=1,
)


@qml.qnode(device)
def circuit(x: float):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliX(0))
print(circuit(0.2))

``` 
works accordingly with `boto3` v1.26 and throws a value-error with `boto3-1.27.0`.

Traceback including the error message:

``` console
  File "example.py", line 3, in <module>
    device = qml.device(
  File ".../python3.10/site-packages/pennylane/__init__.py", line 326, in device
    dev = plugin_device_class(*args, **options)
  File ".../python3.10/site-packages/braket/pennylane_plugin/braket_device.py", line 532, in __init__
    raise ValueError(f"Device {device.name} does not support quantum circuits")
ValueError: Device SV1 does not support quantum circuits
```

This may be an expected error message (due to some deprecation which I couldn't find any notes about) or an incompatibility issue with the plugin that requires a fix. 

**System information**
- Amazon Braket Python SDK v1.47.0
- Amazon Braket Python Schemas v1.17.0
- Amazon Braket Python Default Simulator version v1.16.0
- Python v3.10

**Comment by christianbmadsen** [comment]
@maliasadi Thank you for reporting this. For now we ask that you pin your boto3 version similar to what has been done in https://github.com/aws/amazon-braket-sdk-python/pull/598/files. We are actively looking at a fix to allow newer versions of boto3 with the Amazon Braket Python SDK.
