### ISSUE TITLE
Allow retrieving a batch of tasks together via a batch ARN

### ISSUE THREAD

**Issue by lillian542** [aws/amazon-braket-sdk-python#630]
**Describe the feature you'd like**
I would like a batch ID of some kind, analogous to a task ARN, to be assigned to a batch created by `device.run_batch`, so that I can use a single string to recall the data from a batch at a later time.

**How would this feature be used? Please describe.**
Let's say I've defined a rabi_sequence with a FreeParameter for length, and use it to make a list of pulse sequences, then execute them as a batch, as is done in the Bring Up example notebook. If I want to pull up the results again later, after my kernel has closed, I would like after submitting the batch to run:
```
batch_arn = batch.metadata()["quantumBatchArn"]
```
or maybe just something like
```
batch_arn = batch.arn
```
to retrieve a single ID string. I would then save that string and later use it to retrieve the batch:
```
from braket.aws import AwsQuantumTaskBatch
batch = AwsQuantumTaskBatch(batch_id=batch_arn)
```

**Describe alternatives you've considered**
Currently I have an upload notebook and a data notebook. Once I run something in the upload notebook, I copy-paste the relevant tasks into the data notebook. This allows me to keep track of the strings I will need to retrieve the batch data later, and keep them together, but a shared ID for the batch that allowed it to be recalled as a single object would be easier to keep track of and use than long lists of task ARN strings.

**Comment by math411** [comment]
Hello and thank you for the suggestion! Would using use [search_jobs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/braket/client/search_jobs.html) with a [job tag](https://github.com/aws/amazon-braket-sdk-python/blob/main/src/braket/jobs/quantum_job_creation.py#L130) suit your use case?

**Comment by kshitijc** [comment]
Hello, 

You might be able to leverage [resource tags](https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html) in this case. When you are creating the tasks using `device.run_batch()`, you could pass in a tag value:

```
batch = device.run_batch(circuits, shots=100, tags={"my_batch_1": "foo"})
```

You can later use this tag value to retrieve all the tasks which were tagged with this specific tag value:

```
import boto3

client = boto3.client('resourcegroupstaggingapi')
response = client.get_resources(
    TagFilters=[
        {
            'Key': 'my_batch_1'
        },
    ],
)
tasks = [t["ResourceARN"] for t in response["ResourceTagMappingList"]]
```

Please let us know if this solves the problem @lillian542. Thanks!

**Comment by lillian542** [comment]
@kshitijc Sorry for the delayed response - I was away for a couple of weeks. Thanks for the suggestion, I'll try it out and let you know once the tasks have run!

**Comment by lillian542** [comment]
Unfortunately this didn't work; I'm not sure where I went wrong. I created the tasks like this:

```
import pennylane as qml
from braket.pulse import ConstantWaveform, PulseSequence
from braket.parametric import FreeParameter
import numpy as np

# create device
lucy = qml.device(
    "braket.aws.qubit",
    device_arn="arn:aws:braket:eu-west-2::device/qpu/oqc/Lucy",
    wires=8,
    max_parallel=50,
)


# define pulse sequence
def rabi_pulse(wire, amp):
    """creates a constant drive with amplitude 0.07 (value from AWS example notebook) and 
    drive frequency on-resonance for the given wire"""
    
    frame_name = f"q{wire}_drive"
    readout_name = f"r{wire}_measure"
    phase = 0
    
    waveform = ConstantWaveform(FreeParameter("length"), amp)
    device = lucy._device
    
    drive_frame = device.frames[frame_name]
    readout_frame = device.frames[readout_name]
    

    rabi_sequence = ( 
        PulseSequence()
        .set_frequency(drive_frame, drive_frame.frequency)
        .play(drive_frame, waveform)
        .capture_v0(readout_frame)
    )
    
    return rabi_sequence

# create batch of pulse sequences
wire=7
start_length=10e-9  # minimum pulse duration is 8ns
end_length=80e-9
lengths = np.arange(start_length, end_length, 2e-9)

rabi_sequence = rabi_pulse(wire, amp=0.03)
pulse_sequences = [rabi_sequence(length=length) for length in lengths]

# run with tags
lucy._device.run_batch(pulse_sequences, 
                       shots=1000, 
                       tags={"rabi_on_q7": "foo", "amplitude": "0.03", "User": "Lillian"}, 
                       max_parallel=len(lengths))
```

I can retrieve them individually by their task ARN numbers, but when I try to return using tags like this:
```
import boto3

client = boto3.client('resourcegroupstaggingapi')
response = client.get_resources(
    TagFilters=[
        {
            'Key': 'rabi_on_q7'
        },
    ],
)
tasks = [t["ResourceARN"] for t in response["ResourceTagMappingList"]]
```

I get an empty list. Any pointers on where I went wrong?

**Comment by lillian542** [comment]
I do see the tags on the task in the console

**Comment by lillian542** [comment]
Thanks @kshitijc , that did work.

**Comment by kshitijc** [comment]
That's great! Closing the issue. Please feel free to reopen if you have any other questions. Thanks!
