### ISSUE TITLE
QPU job status

### ISSUE THREAD

**Issue by Qottmann** [aws/amazon-braket-sdk-python#638]
**What did you find confusing? Please describe.**
I am trying to submit a job onto OQC Lucy during its uptime, but find that my jobs are only `CREATED` and not `QUEUED` (single job).

**Describe how documentation can be improved**
 Is there documentation what the different statuses of jobs mean, and, why it is only created and not queued?

**Additional context**
Is there any way to check the status of a device, i.e. obtain information about the queue?

**Comment by math411** [comment]
Hello and thank you for reaching out. Here is some documentation around:
* Tasks status: https://docs.aws.amazon.com/braket/latest/developerguide/braket-task-when.html
* Job status: https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-api.html
As an additional resource, here is some [documentation around the status](https://docs.aws.amazon.com/braket/latest/APIReference/API_GetQuantumTask.html) for tasks.

I shall review the documentation to see if we can improve the explanation for the catalyst for a state change for better clarity.

**Comment by Qottmann** [comment]
Thanks for the quick reply @math411 !

Some info on why the new tasks get stuck in `CREATED` without being `QUEUED`, and what that means, respectively, in the first place, would be great!

**Comment by krneta** [comment]
Hello, generally when a task is in the CREATED status, this means your task has been received by Amazon Braket. Once it moves into QUEUED status, it is now validated by Braket and in the queue waiting to run on the device.

**Comment by Qottmann** [comment]
Thanks! Quick follow up: is it common / expected that jobs get stuck in `CREATED` when the device is very busy?

**Comment by kshitijc** [comment]
While this is not a common behavior, customers may see their task get stuck in the CREATED state. If your task is in the CREATED state, please consider it valid.

**Comment by kshitijc** [comment]
Please reopen this if you have any further questions.
