### ISSUE TITLE
Unclear/Broken behavior of "numerical" FreeParameter

### ISSUE THREAD

**Issue by jcjaskula-aws** [aws/amazon-braket-sdk-python#891]
**Describe the bug**
It is possible to abuse string parsing and create numerical `FreeParameter`s. However, this leads to incoherent output of several parts of the SDK.

**To reproduce**
Here is a list of unexpected behavior:
`type(FreeParameter("1.2").expression)` is a sympy Symbol
`type(FreeParameterExpression("1.2").expression)` is a float.
`Circuit().rx(0, FreeParameterExpression("1.2"))` raises `AttributeError: 'float' object has no attribute 'free_symbols'`
`Circuit().rx(0, FreeParameter("1.2")).to_ir("OPENQASM")` prints lines like `input float 1.2`

**Expected behavior**
`FreeParameter("1.2")`/`FreeParameterExpression("1.2")` should behave as float.

**System information**
- **Amazon Braket Python SDK version**: latest on github
- **Amazon Braket Python Schemas version**:  N/A
- **Amazon Braket Python Default Simulator version**: N/A
- **Python version**: 3.9/3.10

**Additional context**
This came up when trying to translate Qiskit Parameter to FreeParameter.

**Comment by virajvchaudhari** [comment]
Thank you for this issue! We will look into this.
